### ISSUE TITLE
Project maintenance

### ISSUE THREAD

**Issue by scossar** [ligthyear/discourse-curated-home#6]
Hi, great plugin! I've forked it and updated it to work with the latest version of Discourse. https://github.com/scossar/discourse-curated-home-1

I would like to use this plugin in sites that I am currently setting up. It seems that there is also some interest in the Discourse community for it.

Would you prefer me to maintain my own fork of the project, or would you rather that I send you a pull request?

**Comment by ligthyear** [comment]
Hello.

glad you find my work useful. I shut down all work on Discourse. Please go ahead and maintain your own fork and show other people your way. I am also happy to point them to the new repo from now on.
